export const SOCIAL_PLATFORMS = [ 'DISCORD',
                                  'INSTAGRAM',
                                  'LINKEDIN',
                                  'ROBLOX',
                                  'SNAPCHAT',
                                  'SPATIAL',
                                  'TIKTOK',
                                  'TWITCH',
                                  'X',
                                  'YOUTUBE' ];
